---
conf.py:
  copyright: 2016
  project: mindshape_seo
  version: 1.0.0
  release: 1.0.0
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
  latex_documents:
  - - Index
    - mindshape_seo.tex
    - mindshape_seo
    - 
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage
  html_theme_options:
    github_repository: mindshape-GmbH/mindshape_seo
    github_branch: master
...
