---
conf.py:
  copyright: 2016
  project: mindshape SEO
  version: 1.0.8
  release: 1.0.8
  latex_documents:
  - - Index
  html_theme_options:
    github_repository: mindshape-GmbH/mindshape_seo
    github_branch: master
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3start:
    - http://docs.typo3.org/typo3cms/GettingStartedTutorial/
    - null
    t3editors:
    - http://docs.typo3.org/typo3cms/EditorsTutorial/
    - null
...
